(function(){'use strict';
var e="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},h="object"===typeof e.global&&e.global?e.global:"object"===typeof global&&global&&global.Object===Object?global:this;e.global=h;var m="object"===typeof e.exportsNamespace&&e.exportsNamespace?e.exportsNamespace:h;e.exportsNamespace=m;h.Object.freeze(e);var aa={envInfo:e,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.26",globalThis:this};h.Object.freeze(aa);
h.Object.freeze(aa.semantics);var ba=h.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},n=h.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},p=0,q=h.WeakMap?new h.WeakMap:null;function r(a){return function(b,c){return!(!b||!b.$classData||b.$classData.k!==c||b.$classData.i!==a)}}
function ca(a){for(var b in a)return b}function da(a,b,c){var d=new a.G(b[c]);if(c<b.length-1){a=a.n;c+=1;for(var f=d.D,g=0;g<f.length;g++)f[g]=da(a,b,c)}return d}function ea(a){switch(typeof a){case "string":return t(fa);case "number":var b=a|0;return b===a?ga(b)?t(ha):ia(b)?t(ja):t(ka):"number"===typeof a?t(la):t(ma);case "boolean":return t(na);case "undefined":return t(oa);default:return null===a?a.sa():a&&a.$classData&&a.$classData.f.C?t(pa):a&&a.$classData?t(a.$classData):null}}
function qa(a){switch(typeof a){case "string":ra||(ra=(new v).b());for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+ba(65535&(a.charCodeAt(d)|0),c)|0,c=ba(31,c),d=-1+d|0;return b;case "number":w||(w=(new x).b());b=w;c=a|0;if(c===a&&-Infinity!==1/a)b=c;else{if(b.g)b.I[0]=a,b=(new y).v(b.w[b.M]|0,b.w[b.J]|0);else{if(a!==a)b=!1,a=2047,c=+h.Math.pow(2,51);else if(Infinity===a||-Infinity===a)b=0>a,a=2047,c=0;else if(0===a)b=-Infinity===1/a,c=a=0;else if(d=(b=0>a)?-a:a,d>=+h.Math.pow(2,-1022)){a=+h.Math.pow(2,
52);var c=+h.Math.log(d)/.6931471805599453,c=+h.Math.floor(c)|0,c=1023>c?c:1023,f=+h.Math.pow(2,c);f>d&&(c=-1+c|0,f/=2);f=d/f*a;d=+h.Math.floor(f);f-=d;d=.5>f?d:.5<f?1+d:0!==d%2?1+d:d;2<=d/a&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=a);a=c;c=d}else a=d/+h.Math.pow(2,-1074),c=+h.Math.floor(a),d=a-c,a=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c;c=+c;b=(new y).v(c|0,(b?-2147483648:0)|(a|0)<<20|c/4294967296|0)}b=b.x^b.u}return b;case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&
a.$classData||null===a?a.B():null===q?42:sa(a)}}function ta(a,b){var c=h.Object.getPrototypeOf,d=h.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var f=d(a,b);if(void 0!==f)return f;a=c(a)}}function ua(a,b,c){a=ta(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function wa(a,b,c,d){a=ta(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new h.TypeError("super has no setter '"+c+"'.");}
var sa=null!==q?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return qa(a);default:if(null===a)return 0;var b=q.get(a);void 0===b&&(p=b=p+1|0,q.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(h.Object.isSealed(a))return 42;p=b=p+1|0;return a.$idHashCode$0=b}return null===a?0:qa(a)};function ga(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function ia(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function z(){this.y=this.G=void 0;this.i=this.n=this.f=null;this.k=0;this.F=null;this.t="";this.d=this.r=this.s=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function A(a,b,c){var d=new z;d.f={};d.n=null;d.F=a;d.t=b;d.d=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function B(a,b,c,d,f,g,l){var k=new z,u=ca(a);g=g||function(a){return!!(a&&a.$classData&&a.$classData.f[u])};l=l||function(a,b){return!!(a&&a.$classData&&a.$classData.k===b&&a.$classData.i.f[u])};k.y=f;k.f=c;k.t="L"+b+";";k.d=l;k.name=b;k.isInterface=!1;k.isRawJSType=!!d;k.isInstance=g;return k}
function xa(a){function b(a){if("number"===typeof a){this.D=Array(a);for(var b=0;b<a;b++)this.D[b]=f}else this.D=a}var c=new z,d=a.F,f="longZero"==d?C().z:d;b.prototype=new D;b.prototype.constructor=b;b.prototype.$classData=c;var d="["+a.t,g=a.i||a,l=a.k+1;c.G=b;c.y=ya;c.f={a:1,va:1,c:1};c.n=a;c.i=g;c.k=l;c.F=null;c.t=d;c.s=void 0;c.r=void 0;c.d=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return g.d(a,l)};return c}
function t(a){if(!a.s){var b=new E;b.o=a;a.s=b}return a.s}z.prototype.getFakeInstance=function(){return this===fa?"some string":this===na?!1:this===ha||this===ja||this===ka||this===la||this===ma?0:this===pa?C().z:this===oa?void 0:{$classData:this}};z.prototype.getSuperclass=function(){return this.y?t(this.y):null};z.prototype.getComponentType=function(){return this.n?t(this.n):null};
z.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.r||(b.r=xa(b)),b=b.r;return da(b,a,0)};var za=A(!1,"Z","boolean"),Aa=A(0,"C","char"),Ba=A(0,"B","byte"),Ca=A(0,"S","short"),Da=A(0,"I","int"),Ea=A("longZero","J","long"),Fa=A(0,"F","float"),Ga=A(0,"D","double");za.d=r(za);Aa.d=r(Aa);Ba.d=r(Ba);Ca.d=r(Ca);Da.d=r(Da);Ea.d=r(Ea);Fa.d=r(Fa);Ga.d=r(Ga);function F(){}function D(){}D.prototype=F.prototype;F.prototype.b=function(){return this};F.prototype.q=function(){var a=ea(this).o.name,b=(+(this.B()>>>0)).toString(16);return a+"@"+b};F.prototype.B=function(){return sa(this)};F.prototype.toString=function(){return this.q()};var ya=B({a:0},"java.lang.Object",{a:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.k||0;return!(c<b)&&(c>b||!a.i.isPrimitive)}return!1});F.prototype.$classData=ya;function G(){}
G.prototype=new D;G.prototype.constructor=G;G.prototype.b=function(){return this};function Ha(a,b){H().setInterval(function(a){return function(){var b=new h.Date,b=(b.getHours()|0)+"h"+(b.getMinutes()|0)+"m"+(b.getSeconds()|0)+"s";a.innerHTML="Current time is "+b}}(b),1E3)}function Ia(a,b){H().setTimeout(function(a){return function(){a.innerHTML="I am loaded"}}(b),3E3)}
function Ja(a,b){H().setInterval(function(a){return function(){var b=new h.Date;a.innerHTML="Shared date "+(void 0===b?"undefined":b.toString())}}(b),1E3)}function Ka(a,b){a=(new I).K(0);H().setInterval(function(a,b){return function(){a.p=1+a.p|0;b.innerHTML="Invisible tick: "+a.p}}(a,b),1E3)}G.prototype.$classData=B({T:0},"mdocjs$",{T:1,a:1});var J=void 0;function K(){J||(J=(new G).b());return J}function L(){this.P=null;this.l=0}L.prototype=new D;L.prototype.constructor=L;L.prototype.b=function(){return this};
function H(){var a;La||(La=(new L).b());a=La;0===(134217728&a.l)&&0===(134217728&a.l)&&(a.P=h.window,a.l|=134217728);return a.P}L.prototype.$classData=B({U:0},"org.scalajs.dom.package$",{U:1,a:1});var La=void 0;function E(){this.o=null}E.prototype=new D;E.prototype.constructor=E;E.prototype.q=function(){return(this.o.isInterface?"interface ":this.o.isPrimitive?"":"class ")+this.o.name};E.prototype.$classData=B({aa:0},"java.lang.Class",{aa:1,a:1});function M(){this.H=this.N=null}M.prototype=new D;
M.prototype.constructor=M;M.prototype.b=function(){N=this;this.N=Ma(!1);this.H=Ma(!0);return this};M.prototype.$classData=B({ia:0},"java.lang.System$",{ia:1,a:1});var N=void 0;function Na(){N||(N=(new M).b());return N}function O(){}O.prototype=new D;O.prototype.constructor=O;function Pa(){}Pa.prototype=O.prototype;function P(){this.E=null}P.prototype=new D;P.prototype.constructor=P;P.prototype.q=function(){return"DynamicVariable("+this.E+")"};function Qa(a,b){a.E=b;return a}
P.prototype.$classData=B({ka:0},"scala.util.DynamicVariable",{ka:1,a:1});function x(){this.g=!1;this.I=this.w=this.j=null;this.A=!1;this.M=this.J=0}x.prototype=new D;x.prototype.constructor=x;
x.prototype.b=function(){w=this;this.j=(this.g=!!(h.ArrayBuffer&&h.Int32Array&&h.Float32Array&&h.Float64Array))?new h.ArrayBuffer(8):null;this.w=this.g?new h.Int32Array(this.j,0,2):null;this.g&&new h.Float32Array(this.j,0,2);this.I=this.g?new h.Float64Array(this.j,0,1):null;if(this.g)this.w[0]=16909060,a=1===((new h.Int8Array(this.j,0,8))[0]|0);else var a=!0;this.J=(this.A=a)?0:1;this.M=this.A?1:0;return this};x.prototype.$classData=B({la:0},"scala.scalajs.runtime.Bits$",{la:1,a:1});var w=void 0;
function v(){this.l=!1}v.prototype=new D;v.prototype.constructor=v;v.prototype.b=function(){return this};v.prototype.$classData=B({na:0},"scala.scalajs.runtime.RuntimeString$",{na:1,a:1});var ra=void 0;function Q(){}Q.prototype=new D;Q.prototype.constructor=Q;function Ra(){}Ra.prototype=Q.prototype;var oa=B({oa:0},"scala.runtime.BoxedUnit",{oa:1,a:1,c:1},void 0,void 0,function(a){return void 0===a});function I(){this.p=0}I.prototype=new D;I.prototype.constructor=I;
I.prototype.q=function(){return""+this.p};I.prototype.K=function(a){this.p=a;return this};I.prototype.$classData=B({pa:0},"scala.runtime.IntRef",{pa:1,a:1,c:1});var na=B({Z:0},"java.lang.Boolean",{Z:1,a:1,c:1,e:1},void 0,void 0,function(a){return"boolean"===typeof a});function R(){this.O=null}R.prototype=new Pa;R.prototype.constructor=R;R.prototype.b=function(){S=this;this.O=Qa(new P,Na().N);Qa(new P,Na().H);Qa(new P,null);return this};
R.prototype.$classData=B({ja:0},"scala.Console$",{ja:1,wa:1,a:1,ya:1});var S=void 0;function T(){this.z=null}T.prototype=new D;T.prototype.constructor=T;T.prototype.b=function(){U=this;this.z=(new y).v(0,0);return this};
function Sa(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+n(1E9)|0)-(0!==b?n(b):32+n(a)|0)|0,d=c,f=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,g=a,l=b;for(a=b=0;0<=c&&0!==(-2097152&l);){var k=g,u=l,Oa=f,va=d;if(u===va?(-2147483648^k)>=(-2147483648^Oa):(-2147483648^u)>=(-2147483648^va))k=l,u=d,l=g-f|0,k=(-2147483648^l)>(-2147483648^g)?-1+(k-u|0)|0:k-u|0,g=l,l=k,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;k=d>>>1|0;f=f>>>1|0|d<<31;d=k}c=l;if(0===c?-1147483648<=(-2147483648^
g):-2147483648<=(-2147483648^c))c=4294967296*l+ +(g>>>0),g=c/1E9,f=g/4294967296|0,d=b,b=g=d+(g|0)|0,a=(-2147483648^g)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,g=c%1E9|0;c=""+g;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}T.prototype.$classData=B({ma:0},"scala.scalajs.runtime.RuntimeLong$",{ma:1,a:1,xa:1,c:1});var U=void 0;function C(){U||(U=(new T).b());return U}function V(){}V.prototype=new D;V.prototype.constructor=V;function Ta(){}Ta.prototype=V.prototype;
var fa=B({V:0},"java.lang.String",{V:1,a:1,c:1,ua:1,e:1},void 0,void 0,function(a){return"string"===typeof a}),ha=B({$:0},"java.lang.Byte",{$:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return ga(a)}),ma=B({ba:0},"java.lang.Double",{ba:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return"number"===typeof a}),la=B({ca:0},"java.lang.Float",{ca:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return"number"===typeof a}),ka=B({da:0},"java.lang.Integer",{da:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),pa=B({ga:0},"java.lang.Long",{ga:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return!!(a&&a.$classData&&a.$classData.f.C)}),ja=B({ha:0},"java.lang.Short",{ha:1,h:1,a:1,c:1,e:1},void 0,void 0,function(a){return ia(a)});function y(){this.u=this.x=0}y.prototype=new Ra;y.prototype.constructor=y;y.prototype.q=function(){C();var a=this.x,b=this.u;return b===a>>31?""+a:0>b?"-"+Sa(-a|0,0!==a?~b:-b|0):Sa(a,b)};y.prototype.v=function(a,b){this.x=a;this.u=b;return this};
y.prototype.K=function(a){y.prototype.v.call(this,a,a>>31);return this};y.prototype.B=function(){return this.x^this.u};y.prototype.$classData=B({C:0},"scala.scalajs.runtime.RuntimeLong",{C:1,h:1,a:1,c:1,e:1});function W(){}W.prototype=new Ta;W.prototype.constructor=W;function Ua(){}Ua.prototype=W.prototype;W.prototype.W=function(){return this};function X(){}X.prototype=new Ta;X.prototype.constructor=X;X.prototype.b=function(){return this};
X.prototype.$classData=B({fa:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{fa:1,S:1,a:1,Q:1,Y:1,R:1});function Y(){}Y.prototype=new Ua;Y.prototype.constructor=Y;function Va(){}Va.prototype=Y.prototype;Y.prototype.X=function(){W.prototype.W.call(this);return this};function Z(){this.m=this.L=null}Z.prototype=new Va;Z.prototype.constructor=Z;function Ma(a){var b=new Z;b.L=a;(new X).b();Y.prototype.X.call(b);b.m="";return b}
Z.prototype.$classData=B({ea:0},"java.lang.JSConsoleBasedPrintStream",{ea:1,ra:1,qa:1,S:1,a:1,Q:1,Y:1,R:1,ta:1});m["mdoc-js-run5"]=function(a){Ia(K(),a)};m["mdoc-js-run2"]=function(a){Ja(K(),a)};m["mdoc-js-run0"]=function(a){Ha(K(),a)};
m["mdoc-js-run4"]=function(a){K();var b=a.innerHTML;S||(S=(new R).b());a=S.O.E;for(b+="\n";""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.m=""+a.m+b,b="";else{var d=""+a.m+b.substring(0,c);h.console&&(a.L&&h.console.error?h.console.error(d):h.console.log(d));a.m="";b=b.substring(1+c|0)}}};m["mdoc-js-run3"]=function(a){Ka(K(),a)};
}).call(this);
